// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyKFJnjCmUBOaVFKuqBnV5srV6Cppe0Ks',
    appId: '1:993443902152:web:2d79ecdb1a4a7d8ae76bfd',
    messagingSenderId: '993443902152',
    projectId: 'spacex-abaaf',
    authDomain: 'spacex-abaaf.firebaseapp.com',
    storageBucket: 'spacex-abaaf.appspot.com',
    measurementId: 'G-XF3S9HVLDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjnWm9LN1M03sRoVJeHX35z7lNgBHlzro',
    appId: '1:993443902152:android:8c1e88ba6f73f9dce76bfd',
    messagingSenderId: '993443902152',
    projectId: 'spacex-abaaf',
    storageBucket: 'spacex-abaaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBHbpF35G80SeTICBItwA9mmLruRB9dJE',
    appId: '1:993443902152:ios:ce375be23cb93d2de76bfd',
    messagingSenderId: '993443902152',
    projectId: 'spacex-abaaf',
    storageBucket: 'spacex-abaaf.appspot.com',
    iosBundleId: 'com.example.spacex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBHbpF35G80SeTICBItwA9mmLruRB9dJE',
    appId: '1:993443902152:ios:ce375be23cb93d2de76bfd',
    messagingSenderId: '993443902152',
    projectId: 'spacex-abaaf',
    storageBucket: 'spacex-abaaf.appspot.com',
    iosBundleId: 'com.example.spacex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyKFJnjCmUBOaVFKuqBnV5srV6Cppe0Ks',
    appId: '1:993443902152:web:04bfce0e14a502d5e76bfd',
    messagingSenderId: '993443902152',
    projectId: 'spacex-abaaf',
    authDomain: 'spacex-abaaf.firebaseapp.com',
    storageBucket: 'spacex-abaaf.appspot.com',
    measurementId: 'G-LJ8ZQQPCBG',
  );
}
